package com.Monsoon.lists.enums;

public enum MenuState {
    LIST_OF_LISTS_NORMAL,
    ADD_LIST,
    ADD_ITEM,
    BASIC_LIST_NORMAL,
    BASIC_LIST_SELECT_MODE,
    TODO_LIST_NORMAL,
    TODO_LIST_SELECT_MODE,
    QUEUE_LIST_NORMAL,
    QUEUE_LIST_SELECT_MODE,
    MEAL_PLAN_NORMAL,
    MEAL_PLAN_SELECT_MODE;
}
